config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'usd_tickers#show'

  resource :usd_ticker, only: :show
  resource :eur_ticker, only: :show
  resource :rur_ticker, only: :show

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
  
end

app/models/eur_deal.rb
class EurDeal < Deal
  DATA_FETCH_URL = 'https://btc-e.nz/api/3/ticker/btc_eur'

  def self.data_path
    'btc_eur'
  end
end

app/models/rur_deal.rb
class RurDeal < Deal
  DATA_FETCH_URL = 'https://btc-e.nz/api/3/ticker/btc_rur'

  def self.data_path
    'btc_rur'
  end
end

app/models/usd_deal.rb
class UsdDeal < Deal
  DATA_FETCH_URL = 'https://btc-e.nz/api/3/ticker/btc_usd'

  def self.data_path
    'btc_usd'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/eur_tickers_controller.rb
class EurTickersController < ApplicationController
  def show
    @deals = EurDeal.all.where(created_at: 3.hours.ago..Time.now).order(:updated)
  end
end

app/controllers/rur_tickers_controller.rb
class RurTickersController < ApplicationController
  def show
    @deals = RurDeal.all.where(created_at: 3.hours.ago..Time.now).order(:updated)
  end
end

app/controllers/usd_tickers_controller.rb
class UsdTickersController < ApplicationController
  def show
    @deals = UsdDeal.all.where(created_at: 3.hours.ago..Time.now).order(:updated)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/eur_tickers/show.html.slim
h4#ticker-type data-type='eur' EUR ticker

  

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Btc
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag 'https://d3js.org/d3.v3.min.js'
  body
    .menu
      ul.ticker-menu
        li 
          =link_to 'BTC-USD', usd_ticker_path, class: 'usd-ticker-button'
        li 
          =link_to 'BTC-EUR', eur_ticker_path, class: 'eur-ticker-button'
        li 
          =link_to 'BTC-RUR', rur_ticker_path, class: 'rur-ticker-button'
    = yield
    
    script
      | this.chartData = #{@deals.to_json(only: [:updated, :value]).html_safe}

    .chart

app/views/rur_tickers/show.html.slim
h4#ticker-type data-type='rur' USD ticker

app/views/usd_tickers/show.html.slim
h4#ticker-type data-type='usd' USD ticker